import pandas as pd
import numpy as np
import logging
import joblib
from pathlib import Path
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
import warnings
warnings.filterwarnings("ignore")

# ---------------------------------------------------------
# Logging Configuration
# ---------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("FeatureEngineering")

# ---------------------------------------------------------
# Custom Transformer for Domain Features
# ---------------------------------------------------------
class DomainFeatureEngineer(BaseEstimator, TransformerMixin):
    """
    Generates new industry-specific features based on airline financial logic.
    """
    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X_copy = X.copy()
        
        # 1. Revenue per Passenger (Yield Proxy)
        X_copy['revenue_per_passenger'] = X_copy['revenue_usd_m'] / (X_copy['passengers_carried_m'] + 1e-6)
        
        # 2. Fuel Efficiency (Passengers carried per barrel of fuel)
        X_copy['passenger_fuel_efficiency'] = (X_copy['passengers_carried_m'] * 1000000) / (X_copy['quarterly_fuel_bbl'] + 1e-6)
        
        # 3. Fleet Utilization (Passengers per aircraft)
        X_copy['fleet_utilization'] = (X_copy['passengers_carried_m'] * 1000000) / (X_copy['fleet_size'] + 1e-6)
        
        # 4. Crude to Jet Fuel Spread (Market volatility indicator)
        X_copy['jet_crude_spread'] = X_copy['jet_fuel_usd_barrel'] - X_copy['brent_crude_usd_barrel']
        
        # 5. Effective Fuel Price (Price after hedging)
        # Assuming hedge_savings mitigates fuel_cost
        X_copy['effective_fuel_cost_m'] = X_copy['fuel_cost_usd_m'] - X_copy['hedge_savings_usd_m']
        
        logger.info(f"Engineered {5} new domain features. New shape: {X_copy.shape}")
        return X_copy

# ---------------------------------------------------------
# Main Execution: Building the Production Pipeline
# ---------------------------------------------------------
def run_feature_engineering():
    input_path = Path(r"data/interim_data/preprocessed_data.csv")
    output_data_dir = Path(r"data/processed_data")
    output_model_dir = Path(r"models")
    
    output_data_dir.mkdir(parents=True, exist_ok=True)
    output_model_dir.mkdir(parents=True, exist_ok=True)
    
    logger.info(f"Loading preprocessed data from {input_path}")
    df = pd.read_csv(input_path)
    
    # Define Target and Features
    target_col = 'net_profit_usd_m' # Assuming this is the target based on EDA
    X = df.drop(columns=[target_col, 'profit_margin_pct']) # Dropping margin as it's directly tied to profit
    y = df[target_col]
    
    # 1. Instantiate our custom Feature Engineer
    domain_engineer = DomainFeatureEngineer()
    X_engineered = domain_engineer.fit_transform(X)
    
    # 2. Identify Column Types for Scaling/Encoding
    numeric_features = X_engineered.select_dtypes(include=['int64', 'float64']).columns.tolist()
    categorical_features = X_engineered.select_dtypes(include=['object']).columns.tolist()
    
    logger.info(f"Numeric features to scale: {len(numeric_features)}")
    logger.info(f"Categorical features to encode: {len(categorical_features)}")

    # 3. Create the ColumnTransformer
    preprocessor = ColumnTransformer(
        transformers=[
            # ('num', StandardScaler(), numeric_features),
            ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), categorical_features)
        ],
        remainder='passthrough'
    )
    
    # 4. Build the Final Pipeline
    # This pipeline applies Feature Engineering FIRST, then scales/encodes.
    full_pipeline = Pipeline(steps=[
        ('feature_engineering', DomainFeatureEngineer()),
        ('scaling_and_encoding', preprocessor)
    ])
    
    # 5. Fit & Transform the data
    logger.info("Fitting the full feature engineering and scaling pipeline...")
    X_final_array = full_pipeline.fit_transform(X)
    
    # 6. Retrieve column names for the final dataframe
    # Get categorical features names generated by OneHotEncoder
    cat_encoder = full_pipeline.named_steps['scaling_and_encoding'].named_transformers_['cat']
    cat_feature_names = cat_encoder.get_feature_names_out(categorical_features).tolist()
    final_feature_names = numeric_features + cat_feature_names
    
    # Create final Pandas DataFrame
    X_final_df = pd.DataFrame(X_final_array, columns=final_feature_names)
    X_final_df[target_col] = y.values
    
    # 7. Save Artifacts
    final_data_path = output_data_dir / "model_ready_data.csv"
    pipeline_path = output_model_dir / "feature_pipeline.pkl"
    
    X_final_df.to_csv(final_data_path, index=False)
    joblib.dump(full_pipeline, pipeline_path)
    
    logger.info(f"✅ Final model-ready dataset saved to: {final_data_path}")
    logger.info(f"✅ Scikit-Learn Pipeline saved to: {pipeline_path}")

if __name__ == "__main__":
    run_feature_engineering()